/*
 *  setlogfilecommand.cpp
 *  Mothur
 *
 *  Created by westcott on 4/27/10.
 *  Copyright 2010 Schloss Lab. All rights reserved.
 *
 */

#include "setlogfilecommand.h"
#include "commandparameters/booleanparameter.h"
#include "commandparameters/outputfileparameter.h"


 //**********************************************************************************************************************
void SetLogFileCommand::setParameters() {
	try {
		parameters.add(new BooleanParameter(append, "append", false));
		parameters.add(new OutputFileParameter(logFileName, "name", true, true));
		parameters.addStandardParameters(inputDir, outputDir);
	}
	catch (exception& e) {
		LOG(FATAL) << e.what() << " in SetLogFileCommand, setParameters";
		exit(1);
	}
}
//**********************************************************************************************************************
string SetLogFileCommand::getHelpString() {
	try {
		string helpString = "The set.logfile command can be used to provide a specific name for your logfile and/or to append the log generated by mothur to an existing file.\n";
		"The set.logfile command parameters are name and append, name is required. Append is set to false by default.\n";
		"The set.logfile command should be in the following format: set.logfile(name=yourLogFileName, append=T).\n";
		"Example set.logfile(name=/Users/lab/desktop/output.txt, append=T).\n";
		"Note: No spaces between parameter labels (i.e. name), '=' and parameters (i.e.yourLogFileName).\n";
		return helpString;
	}
	catch (exception& e) {
		LOG(FATAL) << e.what() << " in SetLogFileCommand, getHelpString";
		exit(1);
	}
}
//**********************************************************************************************************************

int SetLogFileCommand::execute() {

	string directory = File::getPath(logFileName);
	if (directory == "" || File::dirCheck(directory)) {
		settings.setLogFileName(logFileName, append);
	}
	return 0;
}
//**********************************************************************************************************************/
